import express from 'express';
import catalogController from '../controllers/catalogController.js';
import middlewareController from '../controllers/middlewareController.js';
const router = express.Router();
router.get('/', catalogController.getAllCatalog);
router.get('/:id', catalogController.getCatalog);
router.post('/', middlewareController.verifyTokenAndAdminAuth, middlewareController.validateCatalogRequest, middlewareController.isRequestValidated, catalogController.addCatalog);
router.put('/:id', middlewareController.verifyTokenAndAdminAuth, catalogController.updateCatalog);
router.delete('/:id', middlewareController.verifyTokenAndAdminAuth, catalogController.deleteCatalog);
export default router;